### ISSUE TITLE
error: failed to build archive: No such file or directory

### ISSUE THREAD

**Issue by ltfschoen** [a16z/helios#260] opened 2023-08-18 01:45 UTC
Sometimes when I run `cargo run -p helios --example <example_name>` using the code in this PR https://github.com/a16z/helios/pull/253 I get the following error. 
To overcome the error all I have to do is to run the same command again with no other changes, but what is causing me to have to do that?

```
error: failed to build archive: No such file or directory
```

**Comment by ncitron** [comment] 2023-09-13 23:02
Closing as I cannot reproduce and suspect this is a cargo issue rather than a Helios one.

**Closed by ncitron** 2023-09-13 23:02 UTC
